services:
  - type: web
    name: yt-audio-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
